## See the README.md file for more information

## load dependencies
install.packages("data.table")
install.packages("dplyr")

library(data.table)
library(dplyr)

setwd("UCI HAR Dataset")

## load and merge data to create one data set
dat <- function(){
setwd("test")
y1 <- read.table("y_test.txt", stringsAsFactors = FALSE)
x1 <- read.table("X_test.txt", stringsAsFactors = FALSE)
subject1 <- read.table("subject_test.txt", stringsAsFactors = FALSE)
setwd("UCI HAR Dataset")
setwd("train")
y2 <- read.table("y_train.txt", stringsAsFactors = FALSE)
x2 <- read.table("X_train.txt", stringsAsFactors = FALSE)
subject2 <- read.table("subject_train.txt", stringsAsFactors = FALSE)
y <- rbind(y1, y2)
x <- rbind(x1, x2)
subject <- rbind(subject1, subject2)
td <- cbind(x, y, subject) }

## Extracts only the data on the mean and standard deviation for each measurement
setwd("UCI HAR Dataset")
colname <- read.table("features.txt")
colnames <- as.character(colname[,1])
colnames(td) <- c(colnames, "activity", "subject")
td2 <- select(td, c(1, 2, 3, 4, 5, 6, 41, 42, 43, 44, 45, 46, 81, 82, 83, 84, 85, 86, 121,
                    122, 123, 124, 125, 126, 161, 162, 163, 164, 165, 166, 201, 202, 214, 
                    215, 227, 228, 240, 241, 253, 254, 266, 267, 268, 269, 270, 271, 345, 
                    346, 347, 348, 349, 350, 424, 425, 426, 427, 428, 429, 503, 504, 516, 
                    517, 529, 530, 542, 543, 562, 563))

## based on activity number, uses descriptive activity names to name the activities
activity_name <- character()
for (i in 1:10299) {
      a <- td2[i, 67]
      if (a == "1") {a <- "WALKING"}
      else if (a == 2) {a <- "WALKING_UPSTAIRS"}
      else if (a == 3) {a <- "WALKING_DOWNSTAIRS"}
      else if (a == 4) {a <- "SITTING"}
      else if (a == 5) {a <- "STANDING"}
      else {a <- "LAYING"}
      activity_name <- c(activity_name, a)
}
td2 <- cbind(td2, activity_name)

### list of new column names 
{colname2 <- c("raw Body acceleration mean X",
"raw Body acceleration mean Y",
"raw Body acceleration mean Z",
"raw Body acceleration standard deviation X",
"raw Body acceleration standard deviation Y",
"raw Body acceleration standard deviation Z",
"raw Body acceleration mad X",
"raw Body acceleration mad Y",
"raw Body acceleration mad Z",
"raw Body acceleration maximum X",
"raw Body acceleration maximum Y",
"raw Body acceleration maximum Z",
"raw Body acceleration minimum X",
"raw Body acceleration minimum Y",
"raw Body acceleration minimum Z",
"raw Body acceleration sma",
"raw Body acceleration energy X",
"raw Body acceleration energy Y",
"raw Body acceleration energy Z",
"raw Body acceleration inner-quartile range X",
"raw Body acceleration inner-quartile range Y",
"raw Body acceleration inner-quartile range Z",
"raw Body acceleration entropy X",
"raw Body acceleration entropy Y",
"raw Body acceleration entropy Z",
"raw Body acceleration Coeff X,1",
"raw Body acceleration Coeff X,2",
"raw Body acceleration Coeff X,3",
"raw Body acceleration Coeff X,4",
"raw Body acceleration Coeff Y,1",
"raw Body acceleration Coeff Y,2",
"raw Body acceleration Coeff Y,3",
"raw Body acceleration Coeff Y,4",
"raw Body acceleration Coeff Z,1",
"raw Body acceleration Coeff Z,2",
"raw Body acceleration Coeff Z,3",
"raw Body acceleration Coeff Z,4",
"raw Body acceleration correlation X,Y",
"raw Body acceleration correlation X,Z",
"raw Body acceleration correlation Y,Z",
"raw gravity acceleration mean X",
"raw gravity acceleration mean Y",
"raw gravity acceleration mean Z",
"raw gravity acceleration standard deviation X",
"raw gravity acceleration standard deviation Y",
"raw gravity acceleration standard deviation Z",
"raw gravity acceleration mad X",
"raw gravity acceleration mad Y",
"raw gravity acceleration mad Z",
"raw gravity acceleration maximum X",
"raw gravity acceleration maximum Y",
"raw gravity acceleration maximum Z",
"raw gravity acceleration minimum X",
"raw gravity acceleration minimum Y",
"raw gravity acceleration minimum Z",
"raw gravity acceleration sma",
"raw gravity acceleration energy X",
"raw gravity acceleration energy Y",
"raw gravity acceleration energy Z",
"raw gravity acceleration inner-quartile range X",
"raw gravity acceleration inner-quartile range Y",
"raw gravity acceleration inner-quartile range Z",
"raw gravity acceleration entropy X",
"raw gravity acceleration entropy Y",
"raw gravity acceleration entropy Z",
"raw gravity acceleration Coeff X,1",
"raw gravity acceleration Coeff X,2",
"raw gravity acceleration Coeff X,3",
"raw gravity acceleration Coeff X,4",
"raw gravity acceleration Coeff Y,1",
"raw gravity acceleration Coeff Y,2",
"raw gravity acceleration Coeff Y,3",
"raw gravity acceleration Coeff Y,4",
"raw gravity acceleration Coeff Z,1",
"raw gravity acceleration Coeff Z,2",
"raw gravity acceleration Coeff Z,3",
"raw gravity acceleration Coeff Z,4",
"raw gravity acceleration correlation X,Y",
"raw gravity acceleration correlation X,Z",
"raw gravity acceleration correlation Y,Z",
"raw Body acceleration jerk mean X",
"raw Body acceleration jerk mean Y",
"raw Body acceleration jerk mean Z",
"raw Body acceleration jerk standard deviation X",
"raw Body acceleration jerk standard deviation Y",
"raw Body acceleration jerk standard deviation Z",
"raw Body acceleration jerk mad X",
"raw Body acceleration jerk mad Y",
"raw Body acceleration jerk mad Z",
"raw Body acceleration jerk maximum X",
"raw Body acceleration jerk maximum Y",
"raw Body acceleration jerk maximum Z",
"raw Body acceleration jerk minimum X",
"raw Body acceleration jerk minimum Y",
"raw Body acceleration jerk minimum Z",
"raw Body acceleration jerk sma",
"raw Body acceleration jerk energy X",
"raw Body acceleration jerk energy Y",
"raw Body acceleration jerk energy Z",
"raw Body acceleration jerk inner-quartile range X",
"raw Body acceleration jerk inner-quartile range Y",
"raw Body acceleration jerk inner-quartile range Z",
"raw Body acceleration jerk entropy X",
"raw Body acceleration jerk entropy Y",
"raw Body acceleration jerk entropy Z",
"raw Body acceleration jerk Coeff X,1",
"raw Body acceleration jerk Coeff X,2",
"raw Body acceleration jerk Coeff X,3",
"raw Body acceleration jerk Coeff X,4",
"raw Body acceleration jerk Coeff Y,1",
"raw Body acceleration jerk Coeff Y,2",
"raw Body acceleration jerk Coeff Y,3",
"raw Body acceleration jerk Coeff Y,4",
"raw Body acceleration jerk Coeff Z,1",
"raw Body acceleration jerk Coeff Z,2",
"raw Body acceleration jerk Coeff Z,3",
"raw Body acceleration jerk Coeff Z,4",
"raw Body acceleration jerk correlation X,Y",
"raw Body acceleration jerk correlation X,Z",
"raw Body acceleration jerk correlation Y,Z",
"raw Body Gyroscopic mean X",
"raw Body Gyroscopic mean Y",
"raw Body Gyroscopic mean Z",
"raw Body Gyroscopic standard deviation X",
"raw Body Gyroscopic standard deviation Y",
"raw Body Gyroscopic standard deviation Z",
"raw Body Gyroscopic mad X",
"raw Body Gyroscopic mad Y",
"raw Body Gyroscopic mad Z",
"raw Body Gyroscopic maximum X",
"raw Body Gyroscopic maximum Y",
"raw Body Gyroscopic maximum Z",
"raw Body Gyroscopic minimum X",
"raw Body Gyroscopic minimum Y",
"raw Body Gyroscopic minimum Z",
"raw Body Gyroscopic sma",
"raw Body Gyroscopic energy X",
"raw Body Gyroscopic energy Y",
"raw Body Gyroscopic energy Z",
"raw Body Gyroscopic inner-quartile range X",
"raw Body Gyroscopic inner-quartile range Y",
"raw Body Gyroscopic inner-quartile range Z",
"raw Body Gyroscopic entropy X",
"raw Body Gyroscopic entropy Y",
"raw Body Gyroscopic entropy Z",
"raw Body Gyroscopic Coeff X,1",
"raw Body Gyroscopic Coeff X,2",
"raw Body Gyroscopic Coeff X,3",
"raw Body Gyroscopic Coeff X,4",
"raw Body Gyroscopic Coeff Y,1",
"raw Body Gyroscopic Coeff Y,2",
"raw Body Gyroscopic Coeff Y,3",
"raw Body Gyroscopic Coeff Y,4",
"raw Body Gyroscopic Coeff Z,1",
"raw Body Gyroscopic Coeff Z,2",
"raw Body Gyroscopic Coeff Z,3",
"raw Body Gyroscopic Coeff Z,4",
"raw Body Gyroscopic correlation X,Y",
"raw Body Gyroscopic correlation X,Z",
"raw Body Gyroscopic correlation Y,Z",
"raw Body Gyroscopic jerk mean X",
"raw Body Gyroscopic jerk mean Y",
"raw Body Gyroscopic jerk mean Z",
"raw Body Gyroscopic jerk standard deviation X",
"raw Body Gyroscopic jerk standard deviation Y",
"raw Body Gyroscopic jerk standard deviation Z",
"raw Body Gyroscopic jerk mad X",
"raw Body Gyroscopic jerk mad Y",
"raw Body Gyroscopic jerk mad Z",
"raw Body Gyroscopic jerk maximum X",
"raw Body Gyroscopic jerk maximum Y",
"raw Body Gyroscopic jerk maximum Z",
"raw Body Gyroscopic jerk minimum X",
"raw Body Gyroscopic jerk minimum Y",
"raw Body Gyroscopic jerk minimum Z",
"raw Body Gyroscopic jerk sma",
"raw Body Gyroscopic jerk energy X",
"raw Body Gyroscopic jerk energy Y",
"raw Body Gyroscopic jerk energy Z",
"raw Body Gyroscopic jerk inner-quartile range X",
"raw Body Gyroscopic jerk inner-quartile range Y",
"raw Body Gyroscopic jerk inner-quartile range Z",
"raw Body Gyroscopic jerk entropy X",
"raw Body Gyroscopic jerk entropy Y",
"raw Body Gyroscopic jerk entropy Z",
"raw Body Gyroscopic jerk Coeff X,1",
"raw Body Gyroscopic jerk Coeff X,2",
"raw Body Gyroscopic jerk Coeff X,3",
"raw Body Gyroscopic jerk Coeff X,4",
"raw Body Gyroscopic jerk Coeff Y,1",
"raw Body Gyroscopic jerk Coeff Y,2",
"raw Body Gyroscopic jerk Coeff Y,3",
"raw Body Gyroscopic jerk Coeff Y,4",
"raw Body Gyroscopic jerk Coeff Z,1",
"raw Body Gyroscopic jerk Coeff Z,2",
"raw Body Gyroscopic jerk Coeff Z,3",
"raw Body Gyroscopic jerk Coeff Z,4",
"raw Body Gyroscopic jerk correlation X,Y",
"raw Body Gyroscopic jerk correlation X,Z",
"raw Body Gyroscopic jerk correlation Y,Z",
"raw Body acceleration Mag mean ",
"raw Body acceleration Mag standard deviation",
"raw Body acceleration Mag mad",
"raw Body acceleration Mag maximum ",
"raw Body acceleration Mag minimum ",
"raw Body acceleration Mag sma",
"raw Body acceleration Mag energy",
"raw Body acceleration Mag inner-quartile range",
"raw Body acceleration Mag entropy",
"raw Body acceleration Mag Coeff 1",
"raw Body acceleration Mag Coeff 2",
"raw Body acceleration Mag Coeff 3",
"raw Body acceleration Mag Coeff 4",
"raw gravity acceleration Mag mean ",
"raw gravity acceleration Mag standard deviation",
"raw gravity acceleration Mag mad",
"raw gravity acceleration Mag maximum ",
"raw gravity acceleration Mag minimum ",
"raw gravity acceleration Mag sma",
"raw gravity acceleration Mag energy",
"raw gravity acceleration Mag inner-quartile range",
"raw gravity acceleration Mag entropy",
"raw gravity acceleration Mag Coeff 1",
"raw gravity acceleration Mag Coeff 2",
"raw gravity acceleration Mag Coeff 3",
"raw gravity acceleration Mag Coeff 4",
"raw Body acceleration jerk Mag mean ",
"raw Body acceleration jerk Mag standard deviation",
"raw Body acceleration jerk Mag mad",
"raw Body acceleration jerk Mag maximum ",
"raw Body acceleration jerk Mag minimum ",
"raw Body acceleration jerk Mag sma",
"raw Body acceleration jerk Mag energy",
"raw Body acceleration jerk Mag inner-quartile range",
"raw Body acceleration jerk Mag entropy",
"raw Body acceleration jerk Mag Coeff 1",
"raw Body acceleration jerk Mag Coeff 2",
"raw Body acceleration jerk Mag Coeff 3",
"raw Body acceleration jerk Mag Coeff 4",
"raw Body Gyroscopic Mag mean ",
"raw Body Gyroscopic Mag standard deviation",
"raw Body Gyroscopic Mag mad",
"raw Body Gyroscopic Mag maximum ",
"raw Body Gyroscopic Mag minimum ",
"raw Body Gyroscopic Mag sma",
"raw Body Gyroscopic Mag energy",
"raw Body Gyroscopic Mag inner-quartile range",
"raw Body Gyroscopic Mag entropy",
"raw Body Gyroscopic Mag Coeff 1",
"raw Body Gyroscopic Mag Coeff 2",
"raw Body Gyroscopic Mag Coeff 3",
"raw Body Gyroscopic Mag Coeff 4",
"raw Body Gyroscopic jerk Mag mean ",
"raw Body Gyroscopic jerk Mag standard deviation",
"raw Body Gyroscopic jerk Mag mad",
"raw Body Gyroscopic jerk Mag maximum ",
"raw Body Gyroscopic jerk Mag minimum ",
"raw Body Gyroscopic jerk Mag sma",
"raw Body Gyroscopic jerk Mag energy",
"raw Body Gyroscopic jerk Mag inner-quartile range",
"raw Body Gyroscopic jerk Mag entropy",
"raw Body Gyroscopic jerk Mag Coeff 1",
"raw Body Gyroscopic jerk Mag Coeff 2",
"raw Body Gyroscopic jerk Mag Coeff 3",
"raw Body Gyroscopic jerk Mag Coeff 4",
"frequency Body acceleration mean X",
"frequency Body acceleration mean Y",
"frequency Body acceleration mean Z",
"frequency Body acceleration standard deviation X",
"frequency Body acceleration standard deviation Y",
"frequency Body acceleration standard deviation Z",
"frequency Body acceleration mad X",
"frequency Body acceleration mad Y",
"frequency Body acceleration mad Z",
"frequency Body acceleration maximum X",
"frequency Body acceleration maximum Y",
"frequency Body acceleration maximum Z",
"frequency Body acceleration minimum X",
"frequency Body acceleration minimum Y",
"frequency Body acceleration minimum Z",
"frequency Body acceleration sma",
"frequency Body acceleration energy X",
"frequency Body acceleration energy Y",
"frequency Body acceleration energy Z",
"frequency Body acceleration inner-quartile range X",
"frequency Body acceleration inner-quartile range Y",
"frequency Body acceleration inner-quartile range Z",
"frequency Body acceleration entropy X",
"frequency Body acceleration entropy Y",
"frequency Body acceleration entropy Z",
"frequency Body acceleration maximum Inds X",
"frequency Body acceleration maximum Inds Y",
"frequency Body acceleration maximum Inds Z",
"frequency Body acceleration mean frequency req X",
"frequency Body acceleration mean frequency req Y",
"frequency Body acceleration mean frequency req Z",
"frequency Body acceleration skewness X",
"frequency Body acceleration kurtosis X",
"frequency Body acceleration skewness Y",
"frequency Body acceleration kurtosis Y",
"frequency Body acceleration skewness Z",
"frequency Body acceleration kurtosis Z",
"frequency Body acceleration bands Energy 1,8",
"frequency Body acceleration bands Energy 9,16",
"frequency Body acceleration bands Energy 17,24",
"frequency Body acceleration bands Energy 25,32",
"frequency Body acceleration bands Energy 33,40",
"frequency Body acceleration bands Energy 41,48",
"frequency Body acceleration bands Energy 49,56",
"frequency Body acceleration bands Energy 57,64",
"frequency Body acceleration bands Energy 1,16",
"frequency Body acceleration bands Energy 17,32",
"frequency Body acceleration bands Energy 33,48",
"frequency Body acceleration bands Energy 49,64",
"frequency Body acceleration bands Energy 1,24",
"frequency Body acceleration bands Energy 25,48",
"frequency Body acceleration bands Energy 1,8",
"frequency Body acceleration bands Energy 9,16",
"frequency Body acceleration bands Energy 17,24",
"frequency Body acceleration bands Energy 25,32",
"frequency Body acceleration bands Energy 33,40",
"frequency Body acceleration bands Energy 41,48",
"frequency Body acceleration bands Energy 49,56",
"frequency Body acceleration bands Energy 57,64",
"frequency Body acceleration bands Energy 1,16",
"frequency Body acceleration bands Energy 17,32",
"frequency Body acceleration bands Energy 33,48",
"frequency Body acceleration bands Energy 49,64",
"frequency Body acceleration bands Energy 1,24",
"frequency Body acceleration bands Energy 25,48",
"frequency Body acceleration bands Energy 1,8",
"frequency Body acceleration bands Energy 9,16",
"frequency Body acceleration bands Energy 17,24",
"frequency Body acceleration bands Energy 25,32",
"frequency Body acceleration bands Energy 33,40",
"frequency Body acceleration bands Energy 41,48",
"frequency Body acceleration bands Energy 49,56",
"frequency Body acceleration bands Energy 57,64",
"frequency Body acceleration bands Energy 1,16",
"frequency Body acceleration bands Energy 17,32",
"frequency Body acceleration bands Energy 33,48",
"frequency Body acceleration bands Energy 49,64",
"frequency Body acceleration bands Energy 1,24",
"frequency Body acceleration bands Energy 25,48",
"frequency Body acceleration jerk mean X",
"frequency Body acceleration jerk mean Y",
"frequency Body acceleration jerk mean Z",
"frequency Body acceleration jerk standard deviation X",
"frequency Body acceleration jerk standard deviation Y",
"frequency Body acceleration jerk standard deviation Z",
"frequency Body acceleration jerk mad X",
"frequency Body acceleration jerk mad Y",
"frequency Body acceleration jerk mad Z",
"frequency Body acceleration jerk maximum X",
"frequency Body acceleration jerk maximum Y",
"frequency Body acceleration jerk maximum Z",
"frequency Body acceleration jerk minimum X",
"frequency Body acceleration jerk minimum Y",
"frequency Body acceleration jerk minimum Z",
"frequency Body acceleration jerk sma",
"frequency Body acceleration jerk energy X",
"frequency Body acceleration jerk energy Y",
"frequency Body acceleration jerk energy Z",
"frequency Body acceleration jerk inner-quartile range X",
"frequency Body acceleration jerk inner-quartile range Y",
"frequency Body acceleration jerk inner-quartile range Z",
"frequency Body acceleration jerk entropy X",
"frequency Body acceleration jerk entropy Y",
"frequency Body acceleration jerk entropy Z",
"frequency Body acceleration jerk maximum Inds X",
"frequency Body acceleration jerk maximum Inds Y",
"frequency Body acceleration jerk maximum Inds Z",
"frequency Body acceleration jerk mean frequency req X",
"frequency Body acceleration jerk mean frequency req Y",
"frequency Body acceleration jerk mean frequency req Z",
"frequency Body acceleration jerk skewness X",
"frequency Body acceleration jerk kurtosis X",
"frequency Body acceleration jerk skewness Y",
"frequency Body acceleration jerk kurtosis Y",
"frequency Body acceleration jerk skewness Z",
"frequency Body acceleration jerk kurtosis Z",
"frequency Body acceleration jerk bands Energy 1,8",
"frequency Body acceleration jerk bands Energy 9,16",
"frequency Body acceleration jerk bands Energy 17,24",
"frequency Body acceleration jerk bands Energy 25,32",
"frequency Body acceleration jerk bands Energy 33,40",
"frequency Body acceleration jerk bands Energy 41,48",
"frequency Body acceleration jerk bands Energy 49,56",
"frequency Body acceleration jerk bands Energy 57,64",
"frequency Body acceleration jerk bands Energy 1,16",
"frequency Body acceleration jerk bands Energy 17,32",
"frequency Body acceleration jerk bands Energy 33,48",
"frequency Body acceleration jerk bands Energy 49,64",
"frequency Body acceleration jerk bands Energy 1,24",
"frequency Body acceleration jerk bands Energy 25,48",
"frequency Body acceleration jerk bands Energy 1,8",
"frequency Body acceleration jerk bands Energy 9,16",
"frequency Body acceleration jerk bands Energy 17,24",
"frequency Body acceleration jerk bands Energy 25,32",
"frequency Body acceleration jerk bands Energy 33,40",
"frequency Body acceleration jerk bands Energy 41,48",
"frequency Body acceleration jerk bands Energy 49,56",
"frequency Body acceleration jerk bands Energy 57,64",
"frequency Body acceleration jerk bands Energy 1,16",
"frequency Body acceleration jerk bands Energy 17,32",
"frequency Body acceleration jerk bands Energy 33,48",
"frequency Body acceleration jerk bands Energy 49,64",
"frequency Body acceleration jerk bands Energy 1,24",
"frequency Body acceleration jerk bands Energy 25,48",
"frequency Body acceleration jerk bands Energy 1,8",
"frequency Body acceleration jerk bands Energy 9,16",
"frequency Body acceleration jerk bands Energy 17,24",
"frequency Body acceleration jerk bands Energy 25,32",
"frequency Body acceleration jerk bands Energy 33,40",
"frequency Body acceleration jerk bands Energy 41,48",
"frequency Body acceleration jerk bands Energy 49,56",
"frequency Body acceleration jerk bands Energy 57,64",
"frequency Body acceleration jerk bands Energy 1,16",
"frequency Body acceleration jerk bands Energy 17,32",
"frequency Body acceleration jerk bands Energy 33,48",
"frequency Body acceleration jerk bands Energy 49,64",
"frequency Body acceleration jerk bands Energy 1,24",
"frequency Body acceleration jerk bands Energy 25,48",
"frequency Body Gyroscopic mean X",
"frequency Body Gyroscopic mean Y",
"frequency Body Gyroscopic mean Z",
"frequency Body Gyroscopic standard deviation X",
"frequency Body Gyroscopic standard deviation Y",
"frequency Body Gyroscopic standard deviation Z",
"frequency Body Gyroscopic mad X",
"frequency Body Gyroscopic mad Y",
"frequency Body Gyroscopic mad Z",
"frequency Body Gyroscopic maximum X",
"frequency Body Gyroscopic maximum Y",
"frequency Body Gyroscopic maximum Z",
"frequency Body Gyroscopic minimum X",
"frequency Body Gyroscopic minimum Y",
"frequency Body Gyroscopic minimum Z",
"frequency Body Gyroscopic sma",
"frequency Body Gyroscopic energy X",
"frequency Body Gyroscopic energy Y",
"frequency Body Gyroscopic energy Z",
"frequency Body Gyroscopic inner-quartile range X",
"frequency Body Gyroscopic inner-quartile range Y",
"frequency Body Gyroscopic inner-quartile range Z",
"frequency Body Gyroscopic entropy X",
"frequency Body Gyroscopic entropy Y",
"frequency Body Gyroscopic entropy Z",
"frequency Body Gyroscopic maximum Inds X",
"frequency Body Gyroscopic maximum Inds Y",
"frequency Body Gyroscopic maximum Inds Z",
"frequency Body Gyroscopic mean frequency req X",
"frequency Body Gyroscopic mean frequency req Y",
"frequency Body Gyroscopic mean frequency req Z",
"frequency Body Gyroscopic skewness X",
"frequency Body Gyroscopic kurtosis X",
"frequency Body Gyroscopic skewness Y",
"frequency Body Gyroscopic kurtosis Y",
"frequency Body Gyroscopic skewness Z",
"frequency Body Gyroscopic kurtosis Z",
"frequency Body Gyroscopic bands Energy 1,8",
"frequency Body Gyroscopic bands Energy 9,16",
"frequency Body Gyroscopic bands Energy 17,24",
"frequency Body Gyroscopic bands Energy 25,32",
"frequency Body Gyroscopic bands Energy 33,40",
"frequency Body Gyroscopic bands Energy 41,48",
"frequency Body Gyroscopic bands Energy 49,56",
"frequency Body Gyroscopic bands Energy 57,64",
"frequency Body Gyroscopic bands Energy 1,16",
"frequency Body Gyroscopic bands Energy 17,32",
"frequency Body Gyroscopic bands Energy 33,48",
"frequency Body Gyroscopic bands Energy 49,64",
"frequency Body Gyroscopic bands Energy 1,24",
"frequency Body Gyroscopic bands Energy 25,48",
"frequency Body Gyroscopic bands Energy 1,8",
"frequency Body Gyroscopic bands Energy 9,16",
"frequency Body Gyroscopic bands Energy 17,24",
"frequency Body Gyroscopic bands Energy 25,32",
"frequency Body Gyroscopic bands Energy 33,40",
"frequency Body Gyroscopic bands Energy 41,48",
"frequency Body Gyroscopic bands Energy 49,56",
"frequency Body Gyroscopic bands Energy 57,64",
"frequency Body Gyroscopic bands Energy 1,16",
"frequency Body Gyroscopic bands Energy 17,32",
"frequency Body Gyroscopic bands Energy 33,48",
"frequency Body Gyroscopic bands Energy 49,64",
"frequency Body Gyroscopic bands Energy 1,24",
"frequency Body Gyroscopic bands Energy 25,48",
"frequency Body Gyroscopic bands Energy 1,8",
"frequency Body Gyroscopic bands Energy 9,16",
"frequency Body Gyroscopic bands Energy 17,24",
"frequency Body Gyroscopic bands Energy 25,32",
"frequency Body Gyroscopic bands Energy 33,40",
"frequency Body Gyroscopic bands Energy 41,48",
"frequency Body Gyroscopic bands Energy 49,56",
"frequency Body Gyroscopic bands Energy 57,64",
"frequency Body Gyroscopic bands Energy 1,16",
"frequency Body Gyroscopic bands Energy 17,32",
"frequency Body Gyroscopic bands Energy 33,48",
"frequency Body Gyroscopic bands Energy 49,64",
"frequency Body Gyroscopic bands Energy 1,24",
"frequency Body Gyroscopic bands Energy 25,48",
"frequency Body acceleration Mag mean ",
"frequency Body acceleration Mag standard deviation",
"frequency Body acceleration Mag mad",
"frequency Body acceleration Mag maximum ",
"frequency Body acceleration Mag minimum ",
"frequency Body acceleration Mag sma",
"frequency Body acceleration Mag energy",
"frequency Body acceleration Mag inner-quartile range",
"frequency Body acceleration Mag entropy",
"frequency Body acceleration Mag maximum Inds",
"frequency Body acceleration Mag mean frequency req",
"frequency Body acceleration Mag skewness",
"frequency Body acceleration Mag kurtosis",
"frequency Body Body acceleration jerk Mag mean ",
"frequency Body Body acceleration jerk Mag standard deviation",
"frequency Body Body acceleration jerk Mag mad",
"frequency Body Body acceleration jerk Mag maximum ",
"frequency Body Body acceleration jerk Mag minimum ",
"frequency Body Body acceleration jerk Mag sma",
"frequency Body Body acceleration jerk Mag energy",
"frequency Body Body acceleration jerk Mag inner-quartile range",
"frequency Body Body acceleration jerk Mag entropy",
"frequency Body Body acceleration jerk Mag maximum Inds",
"frequency Body Body acceleration jerk Mag mean frequency req",
"frequency Body Body acceleration jerk Mag skewness",
"frequency Body Body acceleration jerk Mag kurtosis",
"frequency Body Body Gyroscopic Mag mean ",
"frequency Body Body Gyroscopic Mag standard deviation",
"frequency Body Body Gyroscopic Mag mad",
"frequency Body Body Gyroscopic Mag maximum ",
"frequency Body Body Gyroscopic Mag minimum ",
"frequency Body Body Gyroscopic Mag sma",
"frequency Body Body Gyroscopic Mag energy",
"frequency Body Body Gyroscopic Mag inner-quartile range",
"frequency Body Body Gyroscopic Mag entropy",
"frequency Body Body Gyroscopic Mag maximum Inds",
"frequency Body Body Gyroscopic Mag mean frequency req",
"frequency Body Body Gyroscopic Mag skewness",
"frequency Body Body Gyroscopic Mag kurtosis",
"frequency Body Body Gyroscopic jerk Mag mean ",
"frequency Body Body Gyroscopic jerk Mag standard deviation",
"frequency Body Body Gyroscopic jerk Mag mad",
"frequency Body Body Gyroscopic jerk Mag maximum ",
"frequency Body Body Gyroscopic jerk Mag minimum ",
"frequency Body Body Gyroscopic jerk Mag sma",
"frequency Body Body Gyroscopic jerk Mag energy",
"frequency Body Body Gyroscopic jerk Mag inner-quartile range",
"frequency Body Body Gyroscopic jerk Mag entropy",
"frequency Body Body Gyroscopic jerk Mag maximum Inds",
"frequency Body Body Gyroscopic jerk Mag mean frequency req",
"frequency Body Body Gyroscopic jerk Mag skewness",
"frequency Body Body Gyroscopic jerk Mag kurtosis",
"angle(raw Body acceleration mean ,gravity )",
"angle(raw Body acceleration jerk mean ),gravity mean )",
"angle(raw Body Gyroscopic mean ,gravity mean )",
"angle(raw Body Gyroscopic jerk mean ,gravity mean )",
"angle(X,gravity mean )",
"angle(Y,gravity mean )",
"angle(Z,gravity mean )",
 "activity", "subject", "activity_name") }
## assign descriptive variable names
colnames2 <- colname2[c(1, 2, 3, 4, 5, 6, 41, 42, 43, 44, 45, 46, 81, 82, 83, 84, 85, 86, 
                        121, 122, 123, 124, 125, 126, 161, 162, 163, 164, 165, 166, 201, 202,
                        214, 215, 227, 228, 240, 241, 253, 254, 266, 267, 268, 269, 270, 271,
                        345, 346, 347, 348, 349, 350, 424, 425, 426, 427, 428, 429, 503, 504,
                        516, 517, 529, 530, 542, 543, 562:564)]
colnames(td2) <- c(as.character(colnames2))

## write data to text file for submission
write.table(format(final.data, scientific=TRUE), "tidydata.txt",
            row.names = FALSE, col.names = FALSE, quote=2)

## create groups based on factor variables and take mean
final.data <- aggregate(td2[, 1:(ncol(td2)-2)], by=list(subject = td2$subject, 
                              activity_name = td2$activity_name), mean)

## write data to text file for submission
write.table(format(final.data, scientific=TRUE), "tidydata2.txt",
            row.names = FALSE, col.names = FALSE, quote=2)
